language: python
python:
  - "3.9"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  
# command to run tests
script:
  - pytest --cov=./ --cov-report=xml

after_success:
  - codecov
